// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol ArkanaKeysGlobalProtocol {
    var mySecretAPIKey: Int { get }
    var myPassword: String { get }
}

public protocol ArkanaKeysEnvironmentProtocol {
    var seviceAPIKey: Int { get }
}
