# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
          
    - name: Arkana Setup
      run: |
        gem install arkana

    - name: Generate Arkana Packages
      run: |
        arkana -c .arkana.yml -e .env.keys -i debug -l swift

    - name: Check Swift package dependencies
      id: spm-dep-check
      uses: MarcoEidinger/swift-package-dependencies-check@2.3.2
      with:
         isMutating: true
         failWhenOutdated: false
          
    - name: Build
      run: |
        xcodebuild build -project ArkanaDemo.xcodeproj -scheme ArkanaDemo clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No
